### ISSUE TITLE
Decide on output format 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Noise#2]
An output format should be decided. One option is to send a 2d matrix of certain granularity (i.e raster) 
![image](https://user-images.githubusercontent.com/14296774/56977085-694a4780-6b42-11e9-892b-8022aaa13ed8.png)

This will allow for a clear association between the grid cells and the data. Also, these reduces the need to provide an overly-detailed analysis for a the gridded area

**Comment by andredaa** [comment]
sorry, I didn't see that.

**Comment by andredaa** [comment]
I think putting a geoJson on top shouldn't be too difficult. Which give much more detailed outlines of the noise-isochromes. I will try to put it on top and make a screenshot

**Comment by RELNO** [comment]
This should adhere to https://github.com/CityScope/CSL_Hamburg_Grasbrook/issues/36

**Comment by andredaa** [comment]
Here is an example result: 
https://github.com/CityScope/CSL_Hamburg_Noise/blob/master/sample_result.geojson
