### ISSUE TITLE
sample_result.geojson square areas 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Noise#6]
https://github.com/CityScope/CSL_Hamburg_Noise/blob/master/sample_result.geojson appears to still contain the confining area squares

**Comment by andredaa** [comment]
The confining areas are showing any noise level below 45db. 
They are characterized by the property "idiso" : 0.
I would argue it is a matter of front-end visualization to choose a color for this area - or to decide not to show it at all. 

> "type": "Feature",
> 		"properties": {
> 			"cell_id": 1,
> 			"idiso": 0
> }

The creators of the noise computing software, for example chose to make it green. 
![grafik](https://user-images.githubusercontent.com/4631906/61358464-a3da9b00-a87a-11e9-8bb5-12bc986fe5ba.png)
